# Generated by Django 3.1.4 on 2020-12-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chrom', models.CharField(max_length=100)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('c_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_type', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_type', models.CharField(blank=True, max_length=100, null=True)),
                ('qual', models.CharField(blank=True, max_length=100, null=True)),
                ('filtered', models.CharField(blank=True, max_length=100, null=True)),
                ('cabbage_id', models.IntegerField(db_column='cabbage_id')),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('snp_orign', models.CharField(blank=True, max_length=100, null=True)),
                ('snp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'accessions_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cabbagedata',
            options={'managed': False},
        ),
    ]
