# Generated by Django 3.1.4 on 2020-12-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotype', '0002_auto_20201208_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabbageInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brapa_id', models.CharField(max_length=100)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('method_classfication', models.CharField(blank=True, max_length=100, null=True)),
                ('line_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('line_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cabbage_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Accessions',
        ),
        migrations.DeleteModel(
            name='CabbageData',
        ),
    ]
